----Building on date 2025-02-25


insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(1,'xu5QiEV70jz',current_date,current_date,216157,'Daily_Number of Individuals who received their life-saving ARV pickup Female, 0-14 yrs','SWO.1','Number of Individuals who received their life-saving ARV pickup',false,4675,'#{FsbhM7YjtPd.jHbYX4UQbDa}','Daily_Number of Individuals who received their life-saving ARV pickup Female, 0-14 yrs',1,'Daily_Number of Individuals who received their life-saving ARV pickup Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(2,'rOFY8l65IN8',current_date,current_date,216157,'Daily_Number of Individuals who received their life-saving ARV pickup Female, 15+yrs','SWO.2','Number of Individuals who received their life-saving ARV pickup',false,4675,'#{FsbhM7YjtPd.jICzAYyMmbC}','Daily_Number of Individuals who received their life-saving ARV pickup Female, 15+yrs',1,'Daily_Number of Individuals who received their life-saving ARV pickup Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(3,'06GtRJfDYDb',current_date,current_date,216157,'Daily_Number of Individuals who received their life-saving ARV pickup Male, 0-14 yrs','SWO.3','Number of Individuals who received their life-saving ARV pickup',false,4675,'#{FsbhM7YjtPd.fnvTSSasF0C}','Daily_Number of Individuals who received their life-saving ARV pickup Male, 0-14 yrs',1,'Daily_Number of Individuals who received their life-saving ARV pickup Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(4,'VUfXfJJjpdV',current_date,current_date,216157,'Daily_Number of Individuals who received their life-saving ARV pickup Male, 15+yrs','SWO.4','Number of Individuals who received their life-saving ARV pickup',false,4675,'#{FsbhM7YjtPd.WAcGT7f0mGR}','Daily_Number of Individuals who received their life-saving ARV pickup Male, 15+yrs',1,'Daily_Number of Individuals who received their life-saving ARV pickup Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(5,'QpYibRskAEz',current_date,current_date,216157,'Daily_Number of HIV positive clients started on life-saving ART Female, 0-14 yrs','SWO.5','Number of HIV positive clients started on life-saving ART',false,4675,'#{m29RCiNKERb.jHbYX4UQbDa}','Daily_Number of HIV positive clients started on life-saving ART Female, 0-14 yrs',1,'Daily_Number of HIV positive clients started on life-saving ART Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(6,'EPRxqA2PWVc',current_date,current_date,216157,'Daily_Number of HIV positive clients started on life-saving ART Female, 15+yrs','SWO.6','Number of HIV positive clients started on life-saving ART',false,4675,'#{m29RCiNKERb.jICzAYyMmbC}','Daily_Number of HIV positive clients started on life-saving ART Female, 15+yrs',1,'Daily_Number of HIV positive clients started on life-saving ART Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(7,'9EhWqbNZyep',current_date,current_date,216157,'Daily_Number of HIV positive clients started on life-saving ART Male, 0-14 yrs','SWO.7','Number of HIV positive clients started on life-saving ART',false,4675,'#{m29RCiNKERb.fnvTSSasF0C}','Daily_Number of HIV positive clients started on life-saving ART Male, 0-14 yrs',1,'Daily_Number of HIV positive clients started on life-saving ART Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(8,'1Q5GL7RMppT',current_date,current_date,216157,'Daily_Number of HIV positive clients started on life-saving ART Male, 15+yrs','SWO.8','Number of HIV positive clients started on life-saving ART',false,4675,'#{m29RCiNKERb.WAcGT7f0mGR}','Daily_Number of HIV positive clients started on life-saving ART Male, 15+yrs',1,'Daily_Number of HIV positive clients started on life-saving ART Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(9,'1M8CD528E5V',current_date,current_date,216157,'Daily_Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4) Female, 0-14 yrs','SWO.9','Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4)',false,4675,'#{C6F0KcCBHZE.jHbYX4UQbDa}','Daily_Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4) Female, 0-14 yrs',1,'Daily_Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4) Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(10,'mgOlcpItD5H',current_date,current_date,216157,'Daily_Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4) Female, 15+yrs','SWO.10','Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4)',false,4675,'#{C6F0KcCBHZE.jICzAYyMmbC}','Daily_Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4) Female, 15+yrs',1,'Daily_Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4) Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(11,'NOu33QGOp79',current_date,current_date,216157,'Daily_Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4) Male, 0-14 yrs','SWO.11','Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4)',false,4675,'#{C6F0KcCBHZE.fnvTSSasF0C}','Daily_Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4) Male, 0-14 yrs',1,'Daily_Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4) Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(12,'WofhDmGtYnf',current_date,current_date,216157,'Daily_Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4) Male, 15+yrs','SWO.12','Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4)',false,4675,'#{C6F0KcCBHZE.WAcGT7f0mGR}','Daily_Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4) Male, 15+yrs',1,'Daily_Number of individuals diagnosed with Advanced HIV Diseases  (including children < 5 irrespective of CD4) Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(13,'TOuAoUm3uJV',current_date,current_date,216157,'Daily_Number of viral load samples collected from eligible clients Female, 0-14 yrs','SWO.13','Number of viral load samples collected from eligible clients',false,4675,'#{HENk9uc6T88.jHbYX4UQbDa}','Daily_Number of viral load samples collected from eligible clients Female, 0-14 yrs',1,'Daily_Number of viral load samples collected from eligible clients Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(14,'gdyNVKEJMjh',current_date,current_date,216157,'Daily_Number of viral load samples collected from eligible clients Female, 15+yrs','SWO.14','Number of viral load samples collected from eligible clients',false,4675,'#{HENk9uc6T88.jICzAYyMmbC}','Daily_Number of viral load samples collected from eligible clients Female, 15+yrs',1,'Daily_Number of viral load samples collected from eligible clients Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(15,'cx3mLVUvgdw',current_date,current_date,216157,'Daily_Number of viral load samples collected from eligible clients Male, 0-14 yrs','SWO.15','Number of viral load samples collected from eligible clients',false,4675,'#{HENk9uc6T88.fnvTSSasF0C}','Daily_Number of viral load samples collected from eligible clients Male, 0-14 yrs',1,'Daily_Number of viral load samples collected from eligible clients Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(16,'4Ah7664ZvEb',current_date,current_date,216157,'Daily_Number of viral load samples collected from eligible clients Male, 15+yrs','SWO.16','Number of viral load samples collected from eligible clients',false,4675,'#{HENk9uc6T88.WAcGT7f0mGR}','Daily_Number of viral load samples collected from eligible clients Male, 15+yrs',1,'Daily_Number of viral load samples collected from eligible clients Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(17,'dgPYEgInhfn',current_date,current_date,216157,'Daily_Number of viral load results received at the health facility Female, 0-14 yrs','SWO.17','Number of viral load results received at the health facility',false,4675,'#{n4Gd6uG5WnB.jHbYX4UQbDa}','Daily_Number of viral load results received at the health facility Female, 0-14 yrs',1,'Daily_Number of viral load results received at the health facility Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(18,'mSp4m2721W4',current_date,current_date,216157,'Daily_Number of viral load results received at the health facility Female, 15+yrs','SWO.18','Number of viral load results received at the health facility',false,4675,'#{n4Gd6uG5WnB.jICzAYyMmbC}','Daily_Number of viral load results received at the health facility Female, 15+yrs',1,'Daily_Number of viral load results received at the health facility Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(19,'ywYVEHPv4xC',current_date,current_date,216157,'Daily_Number of viral load results received at the health facility Male, 0-14 yrs','SWO.19','Number of viral load results received at the health facility',false,4675,'#{n4Gd6uG5WnB.fnvTSSasF0C}','Daily_Number of viral load results received at the health facility Male, 0-14 yrs',1,'Daily_Number of viral load results received at the health facility Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(20,'6UOxbNKPS8q',current_date,current_date,216157,'Daily_Number of viral load results received at the health facility Male, 15+yrs','SWO.20','Number of viral load results received at the health facility',false,4675,'#{n4Gd6uG5WnB.WAcGT7f0mGR}','Daily_Number of viral load results received at the health facility Male, 15+yrs',1,'Daily_Number of viral load results received at the health facility Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(21,'EDSWJ0YVHGF',current_date,current_date,216157,'Daily_Number of Individuals tested for HIV Female, 0-14 yrs','SWO.21','Number of Individuals tested for HIV',false,4675,'#{EedfNtyouI6.jHbYX4UQbDa}','Daily_Number of Individuals tested for HIV Female, 0-14 yrs',1,'Daily_Number of Individuals tested for HIV Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(22,'IqmeYPaJ9MZ',current_date,current_date,216157,'Daily_Number of Individuals tested for HIV Female, 15+yrs','SWO.22','Number of Individuals tested for HIV',false,4675,'#{EedfNtyouI6.jICzAYyMmbC}','Daily_Number of Individuals tested for HIV Female, 15+yrs',1,'Daily_Number of Individuals tested for HIV Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(23,'45NajNa5Pa7',current_date,current_date,216157,'Daily_Number of Individuals tested for HIV Male, 0-14 yrs','SWO.23','Number of Individuals tested for HIV',false,4675,'#{EedfNtyouI6.fnvTSSasF0C}','Daily_Number of Individuals tested for HIV Male, 0-14 yrs',1,'Daily_Number of Individuals tested for HIV Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(24,'HnbyyrXaOtx',current_date,current_date,216157,'Daily_Number of Individuals tested for HIV Male, 15+yrs','SWO.24','Number of Individuals tested for HIV',false,4675,'#{EedfNtyouI6.WAcGT7f0mGR}','Daily_Number of Individuals tested for HIV Male, 15+yrs',1,'Daily_Number of Individuals tested for HIV Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(25,'NAD26N7MZ2p',current_date,current_date,216157,'Daily_Number of Individuals who tested HIV Positive Female, 0-14 yrs','SWO.25','Number of Individuals who tested HIV Positive',false,4675,'#{YCBt0j4ChAg.jHbYX4UQbDa}','Daily_Number of Individuals who tested HIV Positive Female, 0-14 yrs',1,'Daily_Number of Individuals who tested HIV Positive Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(26,'68V2S6lwTS9',current_date,current_date,216157,'Daily_Number of Individuals who tested HIV Positive Female, 15+yrs','SWO.26','Number of Individuals who tested HIV Positive',false,4675,'#{YCBt0j4ChAg.jICzAYyMmbC}','Daily_Number of Individuals who tested HIV Positive Female, 15+yrs',1,'Daily_Number of Individuals who tested HIV Positive Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(27,'q8gFQC7Lvic',current_date,current_date,216157,'Daily_Number of Individuals who tested HIV Positive Male, 0-14 yrs','SWO.27','Number of Individuals who tested HIV Positive',false,4675,'#{YCBt0j4ChAg.fnvTSSasF0C}','Daily_Number of Individuals who tested HIV Positive Male, 0-14 yrs',1,'Daily_Number of Individuals who tested HIV Positive Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(28,'SHIM0sBt0l8',current_date,current_date,216157,'Daily_Number of Individuals who tested HIV Positive Male, 15+yrs','SWO.28','Number of Individuals who tested HIV Positive',false,4675,'#{YCBt0j4ChAg.WAcGT7f0mGR}','Daily_Number of Individuals who tested HIV Positive Male, 15+yrs',1,'Daily_Number of Individuals who tested HIV Positive Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(29,'2GBOMMd9lQX',current_date,current_date,216157,'Daily_Number of EID test conducted  ','SWO.29','Number of EID test conducted',false,4675,'#{wOTarLmBuTP}','Daily_Number of EID test conducted  ',1,'Daily_Number of EID test conducted  ',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(30,'fy7gbbykYgB',current_date,current_date,216157,'Daily_Number of Viral Load samples received at the PCR lab ','SWO.30','Number of Viral Load samples received at the PCR lab',false,4675,'#{pKRUf6hCfdR}','Daily_Number of Viral Load samples received at the PCR lab ',1,'Daily_Number of Viral Load samples received at the PCR lab ',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(31,'ttG8uA92iNo',current_date,current_date,216157,'Daily_Number of viral load test conducted in the PCR labs (For facilities that have PCR labs) ','SWO.31','Number of viral load test conducted in the PCR labs (For facilities that have PCR labs)',false,4675,'#{qw0bwCb7YT3}','Daily_Number of viral load test conducted in the PCR labs (For facilities that have PCR labs) ',1,'Daily_Number of viral load test conducted in the PCR labs (For facilities that have PCR labs) ',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(32,'DyVuUfaucbE',current_date,current_date,216157,'Daily_Number of clients started on life-saving anti-tuberculosis medication Female, 0-14 yrs','SWO.32','Number of clients started on life-saving anti-tuberculosis medication',false,4675,'#{Nom3PTBVpyA.jHbYX4UQbDa}','Daily_Number of clients started on life-saving anti-tuberculosis medication Female, 0-14 yrs',1,'Daily_Number of clients started on life-saving anti-tuberculosis medication Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(33,'TZrZZVyjMJz',current_date,current_date,216157,'Daily_Number of clients started on life-saving anti-tuberculosis medication Female, 15+yrs','SWO.33','Number of clients started on life-saving anti-tuberculosis medication',false,4675,'#{Nom3PTBVpyA.jICzAYyMmbC}','Daily_Number of clients started on life-saving anti-tuberculosis medication Female, 15+yrs',1,'Daily_Number of clients started on life-saving anti-tuberculosis medication Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(34,'CsJAvF1nd4G',current_date,current_date,216157,'Daily_Number of clients started on life-saving anti-tuberculosis medication Male, 0-14 yrs','SWO.34','Number of clients started on life-saving anti-tuberculosis medication',false,4675,'#{Nom3PTBVpyA.fnvTSSasF0C}','Daily_Number of clients started on life-saving anti-tuberculosis medication Male, 0-14 yrs',1,'Daily_Number of clients started on life-saving anti-tuberculosis medication Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(35,'isPZr4LyNZp',current_date,current_date,216157,'Daily_Number of clients started on life-saving anti-tuberculosis medication Male, 15+yrs','SWO.35','Number of clients started on life-saving anti-tuberculosis medication',false,4675,'#{Nom3PTBVpyA.WAcGT7f0mGR}','Daily_Number of clients started on life-saving anti-tuberculosis medication Male, 15+yrs',1,'Daily_Number of clients started on life-saving anti-tuberculosis medication Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(36,'bP4DC4gtTQI',current_date,current_date,216157,'Daily_Number of clients who received life-saving TB Preventive therapy Female, 0-14 yrs','SWO.36','Number of clients who received life-saving TB Preventive therapy',false,4675,'#{DI0QgZCvI11.jHbYX4UQbDa}','Daily_Number of clients who received life-saving TB Preventive therapy Female, 0-14 yrs',1,'Daily_Number of clients who received life-saving TB Preventive therapy Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(37,'j5ZCLEdOz9p',current_date,current_date,216157,'Daily_Number of clients who received life-saving TB Preventive therapy Female, 15+yrs','SWO.37','Number of clients who received life-saving TB Preventive therapy',false,4675,'#{DI0QgZCvI11.jICzAYyMmbC}','Daily_Number of clients who received life-saving TB Preventive therapy Female, 15+yrs',1,'Daily_Number of clients who received life-saving TB Preventive therapy Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(38,'2lu4SUG6zLX',current_date,current_date,216157,'Daily_Number of clients who received life-saving TB Preventive therapy Male, 0-14 yrs','SWO.38','Number of clients who received life-saving TB Preventive therapy',false,4675,'#{DI0QgZCvI11.fnvTSSasF0C}','Daily_Number of clients who received life-saving TB Preventive therapy Male, 0-14 yrs',1,'Daily_Number of clients who received life-saving TB Preventive therapy Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(39,'Hl9WbDftWaC',current_date,current_date,216157,'Daily_Number of clients who received life-saving TB Preventive therapy Male, 15+yrs','SWO.39','Number of clients who received life-saving TB Preventive therapy',false,4675,'#{DI0QgZCvI11.WAcGT7f0mGR}','Daily_Number of clients who received life-saving TB Preventive therapy Male, 15+yrs',1,'Daily_Number of clients who received life-saving TB Preventive therapy Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(40,'8gWhdFkfpOU',current_date,current_date,216157,'Daily_Pregnant and breastfeeding women on PrEP (Started and continuing) Female, 0-14 yrs','SWO.40','Pregnant and breastfeeding women on PrEP (Started and continuing)',false,4675,'#{ecjjfSm7OcF.jHbYX4UQbDa}','Daily_Pregnant and breastfeeding women on PrEP (Started and continuing) Female, 0-14 yrs',1,'Daily_Pregnant and breastfeeding women on PrEP (Started and continuing) Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(41,'BT4V3W9NQ83',current_date,current_date,216157,'Daily_Pregnant and breastfeeding women on PrEP (Started and continuing) Female, 15+yrs','SWO.41','Pregnant and breastfeeding women on PrEP (Started and continuing)',false,4675,'#{ecjjfSm7OcF.jICzAYyMmbC}','Daily_Pregnant and breastfeeding women on PrEP (Started and continuing) Female, 15+yrs',1,'Daily_Pregnant and breastfeeding women on PrEP (Started and continuing) Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(42,'YZDfLibvEul',current_date,current_date,216157,'Daily_Number of EID results received at the health facility Female','SWO.42','Number of EID results received at the health facility',false,4675,'#{PiAoikTE1Zo.jHbYX4UQbDa}','Daily_Number of EID results received at the health facility Female',1,'Daily_Number of EID results received at the health facility Female',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(43,'lDH7680Ehgu',current_date,current_date,216157,'Daily_Number of EID results received at the health facility Male','SWO.43','Number of EID results received at the health facility',false,4675,'#{PiAoikTE1Zo.fnvTSSasF0C}','Daily_Number of EID results received at the health facility Male',1,'Daily_Number of EID results received at the health facility Male',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(44,'RO3Op91I0yo',current_date,current_date,216157,'Daily_Number of positive EID results received at the health facility Female','SWO.44','Number of positive EID results received at the health facility',false,4675,'#{V0t6JwmNQc4.jHbYX4UQbDa}','Daily_Number of positive EID results received at the health facility Female',1,'Daily_Number of positive EID results received at the health facility Female',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(45,'i1B8xBxFLXb',current_date,current_date,216157,'Daily_Number of positive EID results received at the health facility Male','SWO.45','Number of positive EID results received at the health facility',false,4675,'#{V0t6JwmNQc4.fnvTSSasF0C}','Daily_Number of positive EID results received at the health facility Male',1,'Daily_Number of positive EID results received at the health facility Male',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(46,'3r65xWEafoU',current_date,current_date,216157,'Weekly_Number of individuals who received CD4 test Female, 0-14 yrs','SWO.46','Number of individuals who received CD4 test',false,4675,'#{TglvOV13cq7.jHbYX4UQbDa}','Weekly_Number of individuals who received CD4 test Female, 0-14 yrs',1,'Weekly_Number of individuals who received CD4 test Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(47,'rksAUiuV9HP',current_date,current_date,216157,'Weekly_Number of individuals who received CD4 test Female, 15+yrs','SWO.47','Number of individuals who received CD4 test',false,4675,'#{TglvOV13cq7.jICzAYyMmbC}','Weekly_Number of individuals who received CD4 test Female, 15+yrs',1,'Weekly_Number of individuals who received CD4 test Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(48,'IqwA7cZfBF6',current_date,current_date,216157,'Weekly_Number of individuals who received CD4 test Male, 0-14 yrs','SWO.48','Number of individuals who received CD4 test',false,4675,'#{TglvOV13cq7.fnvTSSasF0C}','Weekly_Number of individuals who received CD4 test Male, 0-14 yrs',1,'Weekly_Number of individuals who received CD4 test Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(49,'2TBzpoIqEZ9',current_date,current_date,216157,'Weekly_Number of individuals who received CD4 test Male, 15+yrs','SWO.49','Number of individuals who received CD4 test',false,4675,'#{TglvOV13cq7.WAcGT7f0mGR}','Weekly_Number of individuals who received CD4 test Male, 15+yrs',1,'Weekly_Number of individuals who received CD4 test Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(50,'I9UDvPG22w7',current_date,current_date,216157,'Weekly_Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4) Female, 0-14 yrs','SWO.50','Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4)',false,4675,'#{TD9rBaz1IeN.jHbYX4UQbDa}','Weekly_Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4) Female, 0-14 yrs',1,'Weekly_Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4) Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(51,'OWoHbRERoby',current_date,current_date,216157,'Weekly_Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4) Female, 15+yrs','SWO.51','Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4)',false,4675,'#{TD9rBaz1IeN.jICzAYyMmbC}','Weekly_Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4) Female, 15+yrs',1,'Weekly_Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4) Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(52,'oKA67C69THN',current_date,current_date,216157,'Weekly_Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4) Male, 0-14 yrs','SWO.52','Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4)',false,4675,'#{TD9rBaz1IeN.fnvTSSasF0C}','Weekly_Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4) Male, 0-14 yrs',1,'Weekly_Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4) Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(53,'T6jO7K4xdYU',current_date,current_date,216157,'Weekly_Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4) Male, 15+yrs','SWO.53','Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4)',false,4675,'#{TD9rBaz1IeN.WAcGT7f0mGR}','Weekly_Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4) Male, 15+yrs',1,'Weekly_Number of individuals with CD4 count test below 200 (including children < 5 irrespective of CD4) Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(54,'darAL7G7k8g',current_date,current_date,216157,'Weekly_Number of ART clients who were due for ARV refill Female, 0-14 yrs','SWO.54','Number of ART clients who were due for ARV refill',false,4675,'#{OM4W42vOPdU.jHbYX4UQbDa}','Weekly_Number of ART clients who were due for ARV refill Female, 0-14 yrs',1,'Weekly_Number of ART clients who were due for ARV refill Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(55,'XAmMzoDgnLS',current_date,current_date,216157,'Weekly_Number of ART clients who were due for ARV refill Female, 15+yrs','SWO.55','Number of ART clients who were due for ARV refill',false,4675,'#{OM4W42vOPdU.jICzAYyMmbC}','Weekly_Number of ART clients who were due for ARV refill Female, 15+yrs',1,'Weekly_Number of ART clients who were due for ARV refill Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(56,'Y5C8nzpVKwT',current_date,current_date,216157,'Weekly_Number of ART clients who were due for ARV refill Male, 0-14 yrs','SWO.56','Number of ART clients who were due for ARV refill',false,4675,'#{OM4W42vOPdU.fnvTSSasF0C}','Weekly_Number of ART clients who were due for ARV refill Male, 0-14 yrs',1,'Weekly_Number of ART clients who were due for ARV refill Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(57,'9AbjCEYx0lQ',current_date,current_date,216157,'Weekly_Number of ART clients who were due for ARV refill Male, 15+yrs','SWO.57','Number of ART clients who were due for ARV refill',false,4675,'#{OM4W42vOPdU.WAcGT7f0mGR}','Weekly_Number of ART clients who were due for ARV refill Male, 15+yrs',1,'Weekly_Number of ART clients who were due for ARV refill Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(58,'eILTtoyRzga',current_date,current_date,216157,'Weekly_Number of clients due for viral load testing Female, 0-14 yrs','SWO.58','Number of clients due for viral load testing',false,4675,'#{DAuUDCHEXcR.jHbYX4UQbDa}','Weekly_Number of clients due for viral load testing Female, 0-14 yrs',1,'Weekly_Number of clients due for viral load testing Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(59,'n93hK2luFNw',current_date,current_date,216157,'Weekly_Number of clients due for viral load testing Female, 15+yrs','SWO.59','Number of clients due for viral load testing',false,4675,'#{DAuUDCHEXcR.jICzAYyMmbC}','Weekly_Number of clients due for viral load testing Female, 15+yrs',1,'Weekly_Number of clients due for viral load testing Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(60,'gfw5916kjSM',current_date,current_date,216157,'Weekly_Number of clients due for viral load testing Male, 0-14 yrs','SWO.60','Number of clients due for viral load testing',false,4675,'#{DAuUDCHEXcR.fnvTSSasF0C}','Weekly_Number of clients due for viral load testing Male, 0-14 yrs',1,'Weekly_Number of clients due for viral load testing Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(61,'ztUEJ7e0rrY',current_date,current_date,216157,'Weekly_Number of clients due for viral load testing Male, 15+yrs','SWO.61','Number of clients due for viral load testing',false,4675,'#{DAuUDCHEXcR.WAcGT7f0mGR}','Weekly_Number of clients due for viral load testing Male, 15+yrs',1,'Weekly_Number of clients due for viral load testing Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(62,'N8T52Fvzk9r',current_date,current_date,216157,'Weekly_Number of VL samples sent to PCR lab Female, 0-14 yrs','SWO.62','Number of VL samples sent to PCR lab',false,4675,'#{GDwJrRuWMhU.jHbYX4UQbDa}','Weekly_Number of VL samples sent to PCR lab Female, 0-14 yrs',1,'Weekly_Number of VL samples sent to PCR lab Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(63,'Vzv4yRCcv8N',current_date,current_date,216157,'Weekly_Number of VL samples sent to PCR lab Female, 15+yrs','SWO.63','Number of VL samples sent to PCR lab',false,4675,'#{GDwJrRuWMhU.jICzAYyMmbC}','Weekly_Number of VL samples sent to PCR lab Female, 15+yrs',1,'Weekly_Number of VL samples sent to PCR lab Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(64,'EFuoqCJgnR9',current_date,current_date,216157,'Weekly_Number of VL samples sent to PCR lab Male, 0-14 yrs','SWO.64','Number of VL samples sent to PCR lab',false,4675,'#{GDwJrRuWMhU.fnvTSSasF0C}','Weekly_Number of VL samples sent to PCR lab Male, 0-14 yrs',1,'Weekly_Number of VL samples sent to PCR lab Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(65,'goTpHZCvqQT',current_date,current_date,216157,'Weekly_Number of VL samples sent to PCR lab Male, 15+yrs','SWO.65','Number of VL samples sent to PCR lab',false,4675,'#{GDwJrRuWMhU.WAcGT7f0mGR}','Weekly_Number of VL samples sent to PCR lab Male, 15+yrs',1,'Weekly_Number of VL samples sent to PCR lab Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(66,'0A2yAHusHpo',current_date,current_date,216157,'Weekly_Number of clients with viral load results below 1,000 Female, 0-14 yrs','SWO.66','Number of clients with viral load results below 1,000',false,4675,'#{ncLZcUkLV6M.jHbYX4UQbDa}','Weekly_Number of clients with viral load results below 1,000 Female, 0-14 yrs',1,'Weekly_Number of clients with viral load results below 1,000 Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(67,'a5WenIfV3Wx',current_date,current_date,216157,'Weekly_Number of clients with viral load results below 1,000 Female, 15+yrs','SWO.67','Number of clients with viral load results below 1,000',false,4675,'#{ncLZcUkLV6M.jICzAYyMmbC}','Weekly_Number of clients with viral load results below 1,000 Female, 15+yrs',1,'Weekly_Number of clients with viral load results below 1,000 Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(68,'LOEOPjYekvw',current_date,current_date,216157,'Weekly_Number of clients with viral load results below 1,000 Male, 0-14 yrs','SWO.68','Number of clients with viral load results below 1,000',false,4675,'#{ncLZcUkLV6M.fnvTSSasF0C}','Weekly_Number of clients with viral load results below 1,000 Male, 0-14 yrs',1,'Weekly_Number of clients with viral load results below 1,000 Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(69,'f5PKk8CSUNd',current_date,current_date,216157,'Weekly_Number of clients with viral load results below 1,000 Male, 15+yrs','SWO.69','Number of clients with viral load results below 1,000',false,4675,'#{ncLZcUkLV6M.WAcGT7f0mGR}','Weekly_Number of clients with viral load results below 1,000 Male, 15+yrs',1,'Weekly_Number of clients with viral load results below 1,000 Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(70,'HdDwCAzpinO',current_date,current_date,216157,'Weekly_Number of clients screened for TB Female, 0-14 yrs','SWO.70','Number of clients screened for TB',false,4675,'#{ssZLALSIyQz.jHbYX4UQbDa}','Weekly_Number of clients screened for TB Female, 0-14 yrs',1,'Weekly_Number of clients screened for TB Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(71,'45UhHKKE828',current_date,current_date,216157,'Weekly_Number of clients screened for TB Female, 15+yrs','SWO.71','Number of clients screened for TB',false,4675,'#{ssZLALSIyQz.jICzAYyMmbC}','Weekly_Number of clients screened for TB Female, 15+yrs',1,'Weekly_Number of clients screened for TB Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(72,'AbQdAUb7zdz',current_date,current_date,216157,'Weekly_Number of clients screened for TB Male, 0-14 yrs','SWO.72','Number of clients screened for TB',false,4675,'#{ssZLALSIyQz.fnvTSSasF0C}','Weekly_Number of clients screened for TB Male, 0-14 yrs',1,'Weekly_Number of clients screened for TB Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(73,'RlMvwOkRTl9',current_date,current_date,216157,'Weekly_Number of clients screened for TB Male, 15+yrs','SWO.73','Number of clients screened for TB',false,4675,'#{ssZLALSIyQz.WAcGT7f0mGR}','Weekly_Number of clients screened for TB Male, 15+yrs',1,'Weekly_Number of clients screened for TB Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(74,'Q0cLaw3SGDP',current_date,current_date,216157,'Weekly_Number of clients presumptive for TB Female, 0-14 yrs','SWO.74','Number of clients presumptive for TB',false,4675,'#{x7OZHAaDGUR.jHbYX4UQbDa}','Weekly_Number of clients presumptive for TB Female, 0-14 yrs',1,'Weekly_Number of clients presumptive for TB Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(75,'HUCMbtpHZRu',current_date,current_date,216157,'Weekly_Number of clients presumptive for TB Female, 15+yrs','SWO.75','Number of clients presumptive for TB',false,4675,'#{x7OZHAaDGUR.jICzAYyMmbC}','Weekly_Number of clients presumptive for TB Female, 15+yrs',1,'Weekly_Number of clients presumptive for TB Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(76,'BmqkpDKbI0t',current_date,current_date,216157,'Weekly_Number of clients presumptive for TB Male, 0-14 yrs','SWO.76','Number of clients presumptive for TB',false,4675,'#{x7OZHAaDGUR.fnvTSSasF0C}','Weekly_Number of clients presumptive for TB Male, 0-14 yrs',1,'Weekly_Number of clients presumptive for TB Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(77,'GzP5o0e1FV9',current_date,current_date,216157,'Weekly_Number of clients presumptive for TB Male, 15+yrs','SWO.77','Number of clients presumptive for TB',false,4675,'#{x7OZHAaDGUR.WAcGT7f0mGR}','Weekly_Number of clients presumptive for TB Male, 15+yrs',1,'Weekly_Number of clients presumptive for TB Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(78,'Ifj5EUwZ9RQ',current_date,current_date,216157,'Weekly_Number of clients diagnosed with TB Female, 0-14 yrs','SWO.78','Number of clients diagnosed with TB',false,4675,'#{zuadfI8OdTx.jHbYX4UQbDa}','Weekly_Number of clients diagnosed with TB Female, 0-14 yrs',1,'Weekly_Number of clients diagnosed with TB Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(79,'4T5M2XD02dO',current_date,current_date,216157,'Weekly_Number of clients diagnosed with TB Female, 15+yrs','SWO.79','Number of clients diagnosed with TB',false,4675,'#{zuadfI8OdTx.jICzAYyMmbC}','Weekly_Number of clients diagnosed with TB Female, 15+yrs',1,'Weekly_Number of clients diagnosed with TB Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(80,'NjFch0umTKy',current_date,current_date,216157,'Weekly_Number of clients diagnosed with TB Male, 0-14 yrs','SWO.80','Number of clients diagnosed with TB',false,4675,'#{zuadfI8OdTx.fnvTSSasF0C}','Weekly_Number of clients diagnosed with TB Male, 0-14 yrs',1,'Weekly_Number of clients diagnosed with TB Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(81,'d937r0aj8uP',current_date,current_date,216157,'Weekly_Number of clients diagnosed with TB Male, 15+yrs','SWO.81','Number of clients diagnosed with TB',false,4675,'#{zuadfI8OdTx.WAcGT7f0mGR}','Weekly_Number of clients diagnosed with TB Male, 15+yrs',1,'Weekly_Number of clients diagnosed with TB Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(82,'wGFsAvoPOh8',current_date,current_date,216157,'Weekly_Number of clients eligible for TPT Female, 0-14 yrs','SWO.82','Number of clients eligible for TPT',false,4675,'#{yEsnQGzfG95.jHbYX4UQbDa}','Weekly_Number of clients eligible for TPT Female, 0-14 yrs',1,'Weekly_Number of clients eligible for TPT Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(83,'f4qgSgJ8oWA',current_date,current_date,216157,'Weekly_Number of clients eligible for TPT Female, 15+yrs','SWO.83','Number of clients eligible for TPT',false,4675,'#{yEsnQGzfG95.jICzAYyMmbC}','Weekly_Number of clients eligible for TPT Female, 15+yrs',1,'Weekly_Number of clients eligible for TPT Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(84,'JfA3eqC5THI',current_date,current_date,216157,'Weekly_Number of clients eligible for TPT Male, 0-14 yrs','SWO.84','Number of clients eligible for TPT',false,4675,'#{yEsnQGzfG95.fnvTSSasF0C}','Weekly_Number of clients eligible for TPT Male, 0-14 yrs',1,'Weekly_Number of clients eligible for TPT Male, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(85,'MKWQqoAK529',current_date,current_date,216157,'Weekly_Number of clients eligible for TPT Male, 15+yrs','SWO.85','Number of clients eligible for TPT',false,4675,'#{yEsnQGzfG95.WAcGT7f0mGR}','Weekly_Number of clients eligible for TPT Male, 15+yrs',1,'Weekly_Number of clients eligible for TPT Male, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(86,'ygeqvuAXlis',current_date,current_date,216157,'Weekly_Number of new clients registered for ANC Female, 0-14 yrs','SWO.86','Number of new clients registered for ANC',false,4675,'#{MDeNw94C6EY.jHbYX4UQbDa}','Weekly_Number of new clients registered for ANC Female, 0-14 yrs',1,'Weekly_Number of new clients registered for ANC Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(87,'7haMfkhqfmE',current_date,current_date,216157,'Weekly_Number of new clients registered for ANC Female, 15+yrs','SWO.87','Number of new clients registered for ANC',false,4675,'#{MDeNw94C6EY.jICzAYyMmbC}','Weekly_Number of new clients registered for ANC Female, 15+yrs',1,'Weekly_Number of new clients registered for ANC Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(88,'KVS58J0tNnG',current_date,current_date,216157,'Weekly_Partners of Pregnant women tested for HIV ','SWO.88','Partners of Pregnant women tested for HIV',false,4675,'#{jZd60poZ9uH}','Weekly_Partners of Pregnant women tested for HIV ',1,'Weekly_Partners of Pregnant women tested for HIV ',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(89,'u7XpMfUDdcJ',current_date,current_date,216157,'Weekly_Children born to HIV+ mothers who received life-saving ARV propylaxis Female Female','SWO.89','Children born to HIV+ mothers who received life-saving ARV propylaxis',false,4675,'#{gJHYwKUdVcc.jHbYX4UQbDa}','Weekly_Children born to HIV+ mothers who received life-saving ARV propylaxis Female Female',1,'Weekly_Children born to HIV+ mothers who received life-saving ARV propylaxis Female Female',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(90,'yDBuKj12Lcx',current_date,current_date,216157,'Weekly_Children born to HIV+ mothers who received life-saving ARV propylaxis Male Male','SWO.90','Children born to HIV+ mothers who received life-saving ARV propylaxis',false,4675,'#{gJHYwKUdVcc.fnvTSSasF0C}','Weekly_Children born to HIV+ mothers who received life-saving ARV propylaxis Male Male',1,'Weekly_Children born to HIV+ mothers who received life-saving ARV propylaxis Male Male',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(91,'vdGAoOoScQ0',current_date,current_date,216157,'Weekly_Number of  HIV Exposed Infants who had their sample collected for EID testing Female Female','SWO.91','Number of  HIV Exposed Infants who had their sample collected for EID testing',false,4675,'#{b8dn74ZnnVh.jHbYX4UQbDa}','Weekly_Number of  HIV Exposed Infants who had their sample collected for EID testing Female Female',1,'Weekly_Number of  HIV Exposed Infants who had their sample collected for EID testing Female Female',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(92,'tln1fhX7XZE',current_date,current_date,216157,'Weekly_Number of  HIV Exposed Infants who had their sample collected for EID testing Male Male','SWO.92','Number of  HIV Exposed Infants who had their sample collected for EID testing',false,4675,'#{b8dn74ZnnVh.fnvTSSasF0C}','Weekly_Number of  HIV Exposed Infants who had their sample collected for EID testing Male Male',1,'Weekly_Number of  HIV Exposed Infants who had their sample collected for EID testing Male Male',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(93,'uQGoSz7SG5j',current_date,current_date,216157,'Weekly_Number of pregnant and breastfeeding women commenced on life-saving PrEP Female, 0-14 yrs','SWO.93','Number of pregnant and breastfeeding women commenced on life-saving PrEP',false,4675,'#{aplLQlvhU2A.jHbYX4UQbDa}','Weekly_Number of pregnant and breastfeeding women commenced on life-saving PrEP Female, 0-14 yrs',1,'Weekly_Number of pregnant and breastfeeding women commenced on life-saving PrEP Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(94,'kQpdiFEqCzW',current_date,current_date,216157,'Weekly_Number of pregnant and breastfeeding women commenced on life-saving PrEP Female, 15+yrs','SWO.94','Number of pregnant and breastfeeding women commenced on life-saving PrEP',false,4675,'#{aplLQlvhU2A.jICzAYyMmbC}','Weekly_Number of pregnant and breastfeeding women commenced on life-saving PrEP Female, 15+yrs',1,'Weekly_Number of pregnant and breastfeeding women commenced on life-saving PrEP Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(95,'Bfu3S2jItEK',current_date,current_date,216157,'Weekly_Number of pregnant and breastfeeding women returning for life-saving PrEP Female, 0-14 yrs','SWO.95','Number of pregnant and breastfeeding women returning for life-saving PrEP',false,4675,'#{xsRtHY5Uq5o.jHbYX4UQbDa}','Weekly_Number of pregnant and breastfeeding women returning for life-saving PrEP Female, 0-14 yrs',1,'Weekly_Number of pregnant and breastfeeding women returning for life-saving PrEP Female, 0-14 yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(96,'pen4AvFZoES',current_date,current_date,216157,'Weekly_Number of pregnant and breastfeeding women returning for life-saving PrEP Female, 15+yrs','SWO.96','Number of pregnant and breastfeeding women returning for life-saving PrEP',false,4675,'#{xsRtHY5Uq5o.jICzAYyMmbC}','Weekly_Number of pregnant and breastfeeding women returning for life-saving PrEP Female, 15+yrs',1,'Weekly_Number of pregnant and breastfeeding women returning for life-saving PrEP Female, 15+yrs',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(97,'WqjvuDI4jgo',current_date,current_date,216157,'Weekly_Number of VL Result dispatched ','SWO.97','Number of VL Result dispatched',false,4675,'#{f3aD4bSmubb}','Weekly_Number of VL Result dispatched ',1,'Weekly_Number of VL Result dispatched ',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(98,'ANvOp2emWqy',current_date,current_date,216157,'Weekly_Number of EID Samples received ','SWO.98','Number of EID Samples received',false,4675,'#{SiS3CefgYpy}','Weekly_Number of EID Samples received ',1,'Weekly_Number of EID Samples received ',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(99,'5YfJNyWDDVH',current_date,current_date,216157,'Weekly_Number of EID Result dispatched ','SWO.99','Number of EID Result dispatched',false,4675,'#{CfsseCcOSrm}','Weekly_Number of EID Result dispatched ',1,'Weekly_Number of EID Result dispatched ',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(100,'B4hvJfDduIx',current_date,current_date,216157,'Weekly_Number of TLD-90 bottles redistributed ','SWO.100','Number of TLD-90 bottles redistributed',false,4675,'#{TIxh7Fi9DE2}','Weekly_Number of TLD-90 bottles redistributed ',1,'Weekly_Number of TLD-90 bottles redistributed ',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

insert into indicator(indicatorid,uid,created, lastupdated, lastupdatedby, name,shortname,description,annualized,indicatortypeid,numerator,numeratordescription,denominator,denominatordescription,userid,sharing)VALUES(101,'ajBq5BQHgde',current_date,current_date,216157,'Weekly_Number of Determine test kits redistributed ','SWO.101','Number of Determine test kits redistributed',false,4675,'#{F5h8g5OwSh7}','Weekly_Number of Determine test kits redistributed ',1,'Weekly_Number of Determine test kits redistributed ',216157,'{"owner": "RNEoDCt5yu7","users": {},"public": "rw------","external": false,"userGroups": {}}');

